// Generated by LiveScript 1.3.1
(function(){
  var Button, addClickingToAllButtons, addClickingToBigButtons, addClickingToAtButton, resetAllWhenLeaving, resetAllWhenEntering, BigButton, AtButton;
  Button = (function(){
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    Button.buttons = [];
    Button.disableOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          results$.push(button.disable());
        }
      }
      return results$;
    };
    Button.enableOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          results$.push(button.enable());
        }
      }
      return results$;
    };
    Button.resetAll = function(){
      var i$, ref$, len$;
      this.index = 0;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        (fn$.call(this, ref$[i$]));
      }
      function fn$(button){
        button.reset();
      }
    };
    Button.allButtonsClicked = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state !== 'done') {
          return false;
        }
      }
      return true;
    };
    function Button(dom, goodMessage, badMessages, i, callBack){
      var this$ = this;
      this.dom = dom;
      this.goodMessage = goodMessage;
      this.badMessages = badMessages;
      this.i = i;
      this.callBack = callBack;
      this.state = 'enable';
      this.ballon = this.dom.find('.unread');
      this.ballon.addClass('hidden-ballon');
      this.dom.addClass('enable');
      this.dom.click(function(){
        if (this$.state === 'enable') {
          this$.constructor.disableOtherButtons(this$);
          this$.clicked();
          this$.getNumber();
        }
      });
      this.constructor.buttons.push(this);
    }
    prototype.getNumber = function(){
      var this$ = this;
      $.get('/hehe' + this.i, function(number, status){
        if (this$.state === 'clicked') {
          this$.done();
          this$.constructor.enableOtherButtons(this$);
          this$.showNumberInBallon(number);
          BigButton.count(number);
          if (this$.constructor.allButtonsClicked() === true) {
            BigButton.changeBigButtonState();
            if (AtButton.clicked === true) {
              BigButton.ready();
            }
          }
          if (this$.constructor.allButtonsClicked() !== true) {
            if (AtButton.clicked === true) {
              AtButton.clickNextOne();
            }
          }
          this$.successFail(number);
        }
      });
    };
    prototype.enable = function(){
      this.state = "enable";
      this.dom.removeClass("disable");
      this.dom.addClass("enable");
    };
    prototype.disable = function(){
      this.state = "disable";
      this.dom.removeClass("enable");
      this.dom.addClass("disable");
    };
    prototype.clicked = function(){
      this.state = "clicked";
      this.ballon.removeClass('hidden-ballon');
      this.ballon.addClass('waiting-ballon');
      this.ballon.text('...');
    };
    prototype.done = function(){
      this.state = "done";
      this.dom.removeClass("enable");
      this.dom.addClass("disable");
    };
    prototype.reset = function(){
      this.state = "enable";
      this.dom.removeClass('disable');
      this.dom.addClass('enable');
      this.ballon.removeClass(this.state);
      this.ballon.addClass('hidden-ballon');
      this.ballon.text('');
    };
    prototype.showNumberInBallon = function(number){
      this.ballon.text(number);
    };
    prototype.successFail = function(number){
      var success, error;
      if (success = Math.random() > 0.3) {
        this.showMessage(this.goodMessage);
        this.callBack(error = null, number);
      } else {
        this.callBack({
          message: this.badMessages,
          data: number
        });
      }
    };
    prototype.showMessage = function(message){
      console.log(message + "");
    };
    return Button;
  }());
  addClickingToAllButtons = function(){
    var goodMessages, badMessages, i$, ref$, len$;
    goodMessages = ['这是个天大的秘密', '我不知道', '你不知道', '他不知道', '才怪'];
    badMessages = ['这不是个天大的秘密', '我知道', '你知道', '他知道', '才怪'];
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      (fn$.call(this, i$, ref$[i$]));
    }
    function fn$(i, dom){
      var button;
      button = new Button($(dom), goodMessages[i], badMessages[i], i, function(error, number){
        if (error) {
          console.log(error.message + "");
        }
      });
    }
  };
  addClickingToBigButtons = function(){
    var dom, bigButton;
    dom = $('#info-bar');
    bigButton = new BigButton($(dom));
  };
  addClickingToAtButton = function(){
    var dom, atButton;
    dom = $('#icon');
    atButton = new AtButton($(dom));
  };
  $(function(){
    addClickingToAllButtons();
    addClickingToBigButtons();
    addClickingToAtButton();
    resetAllWhenLeaving();
    resetAllWhenEntering();
  });
  resetAllWhenLeaving = function(){
    var all;
    all = $('#bottom-positioner');
    all.mouseleave(function(){
      BigButton.resetLargeButton();
      Button.resetAll();
      AtButton.atButtonReset();
    });
  };
  resetAllWhenEntering = function(){
    var all;
    all = $('#buttom-positoner');
    all.mouseenter(function(){
      BigButton.resetLargeButton();
      Button.resetAll();
      AtButton.atButtonReset();
    });
  };
  BigButton = (function(){
    BigButton.displayName = 'BigButton';
    var prototype = BigButton.prototype, constructor = BigButton;
    BigButton.number = 0;
    BigButton.resetLargeButton = function(){
      this.bigButton.reset();
    };
    BigButton.bigButton;
    BigButton.count = function(newNumber){
      this.number += parseInt(newNumber);
    };
    BigButton.changeBigButtonState = function(){
      this.bigButton.enable();
    };
    BigButton.ready = function(){
      this.bigButton.dom.click();
    };
    prototype.showNumberInBigButton = function(){
      this.showNumberContainer.text(this.constructor.number);
    };
    function BigButton(dom){
      var this$ = this;
      this.dom = dom;
      this.disable();
      this.showNumberContainer = this.dom.find('p');
      this.dom.click(function(){
        if (this$.state === 'enable') {
          this$.showNumberInBigButton();
          this$.disable();
        }
      });
      this.constructor.bigButton = this;
    }
    prototype.disable = function(){
      this.state = 'disable';
      this.dom.removeClass('enable');
      this.dom.addClass('disable');
    };
    prototype.enable = function(){
      this.state = 'enable';
      this.dom.removeClass('disable');
      this.dom.addClass('enable');
    };
    prototype.reset = function(){
      this.state = 'disable';
      this.dom.removeClass('enable');
      this.dom.addClass('disable');
      this.constructor.number = 0;
      this.showNumberContainer.text("");
    };
    return BigButton;
  }());
  AtButton = (function(){
    AtButton.displayName = 'AtButton';
    var prototype = AtButton.prototype, constructor = AtButton;
    AtButton.button;
    AtButton.clicked;
    AtButton.clickNextOne = function(){
      this.button.clickNext();
    };
    AtButton.atButtonReset = function(){
      this.button.reset();
    };
    function AtButton(dom){
      var button, this$ = this;
      this.dom = dom;
      button = this.dom;
      this.state = 'enable';
      this.initialize();
      this.dom.click(function(){
        if (this$.state === 'enable') {
          this$.constructor.clicked = true;
          this$.getRandomNumbers();
          this$.clickNext();
          this$.state = 'disable';
        }
      });
      this.constructor.button = this;
    }
    prototype.enable = function(){
      return this.state = 'enable';
    };
    prototype.disable = function(){
      return this.state = 'disable';
    };
    prototype.reset = function(){
      this.state = 'enable';
      this.constructor.clicked = false;
      return this.index = 0;
    };
    prototype.initialize = function(){
      this.buttons = $('#control-ring .button');
      this.bigButton = $('#info-bar');
      this.index = 0;
      this.buttonSize = 5;
      return this.sequence = ["A", "B", "C", "D", "E"];
    };
    prototype.getRandomNumbers = function(){
      this.sequence.sort(function(){
        return 0.5 - Math.random();
      });
    };
    prototype.clickNext = function(){
      var temp;
      if (this.index < 5) {
        temp = this.sequence[this.index].charCodeAt() - 'A'.charCodeAt();
        this.index = this.index + 1;
        this.buttons[temp].click();
      }
    };
    return AtButton;
  }());
}).call(this);
